/**
 * Points the DUST generated by the script wallet's tNIGHT at another wallet.
 *
 * Usage:
 *   npm run redirect-dust -- <dust-address>   # e.g. a Lace wallet's mn_dust_preprod1... address
 *   npm run redirect-dust                     # point DUST back at the script wallet itself
 *
 * Useful when a browser wallet holds tNIGHT but cannot register it for DUST
 * generation itself: the script wallet's tNIGHT then pays that wallet's fees.
 */

import { DustAddress, MidnightBech32m } from '@midnight-ntwrk/wallet-sdk-address-format';

import { CONFIG, deregisterFromDust, openPreprodWallet, registerForDust, waitFor } from './wallet.js';

const parseDustAddress = (bech32: string): DustAddress => {
  try {
    return DustAddress.codec.decode(CONFIG.networkId, MidnightBech32m.parse(bech32));
  } catch (err) {
    throw new Error(`"${bech32}" is not a ${CONFIG.networkId} DUST address: ${(err as Error).message}`);
  }
};

async function main() {
  const target = process.argv[2];
  const receiver = target ? parseDustAddress(target) : undefined;
  console.log(
    receiver
      ? `🌑 DUST üretimi şu adrese yönlendirilecek: ${target}\n`
      : '🌑 DUST üretimi script cüzdanının kendisine geri alınacak\n',
  );

  const ctx = await openPreprodWallet();

  const registered = ctx.synced.unshielded.availableCoins.filter((c) => c.meta.registeredForDustGeneration);
  if (registered.length > 0) {
    console.log(`⏳ ${registered.length} tNIGHT UTXO'sunun mevcut DUST kaydı kaldırılıyor...`);
    const txId = await deregisterFromDust(ctx);
    console.log(`✅ Kayıt kaldırma işlemi gönderildi: ${txId}`);
    await waitFor(ctx.wallet, (s) => s.unshielded.availableCoins.every((c) => !c.meta.registeredForDustGeneration));
    console.log('✅ Kayıt kaldırıldı\n');
  }

  console.log('⏳ tNIGHT yeniden DUST üretimine kaydediliyor...');
  const txId = await registerForDust(ctx, receiver);
  console.log(`✅ Kayıt işlemi gönderildi: ${txId}`);
  await waitFor(ctx.wallet, (s) => s.unshielded.availableCoins.every((c) => c.meta.registeredForDustGeneration));
  console.log('\n🎉 Tamamlandı. DUST birkaç dakika içinde hedef cüzdanda birikmeye başlar.');

  await ctx.close();
  process.exit(0);
}

main().catch((err) => {
  console.error('\n❌ Hata:', err);
  process.exit(1);
});
